import { Wallet, Transaction, TransactionType } from './types';

export const INITIAL_WALLETS: Wallet[] = [
    { id: 'CASH', name: 'Cash', balance: 2000000, icon: '' },
    { id: 'BRILINK', name: 'BRILink', balance: 2000000, icon: '' },
    { id: 'BRI', name: 'BRI', balance: 2000000, icon: '' },
    { id: 'SEABANK', name: 'Seabank', balance: 2000000, icon: '' },
    { id: 'DANA', name: 'Dana', balance: 2000000, icon: '' },
    { id: 'SHOPEEPAY', name: 'ShopeePay', balance: 2000000, icon: '' },
];

export const INITIAL_CATEGORIES: string[] = [
    'Tarik Tunai',
    'Transfer Bank',
    'Bayar Listrik',
    'Top Up E-Wallet',
    'Bayar Cicilan',
    'Lainnya'
];

export const MOCK_TRANSACTIONS: Transaction[] = [
    {
        id: 'TXN1001',
        date: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
        description: 'Tarik Tunai',
        customer: 'Budi Santoso',
        type: TransactionType.IN,
        amount: 500000,
        margin: 5000,
        wallet: 'BRILINK',
        isPiutang: false,
    },
    {
        id: 'TXN1002',
        date: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
        description: 'Transfer Bank',
        customer: 'Siti Aminah',
        type: TransactionType.OUT,
        amount: 1000000,
        margin: 6500,
        wallet: 'BRI',
        isPiutang: false,
    },
    {
        id: 'TXN1003',
        date: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
        description: 'Bayar Listrik',
        customer: 'Ahmad Yani',
        type: TransactionType.OUT,
        amount: 250000,
        margin: 3000,
        wallet: 'BRILINK',
        isPiutang: true,
    },
    {
        id: 'TXN1004',
        date: new Date(new Date().setDate(new Date().getDate() - 4)).toISOString(),
        description: 'Top Up E-Wallet',
        customer: 'Dewi Lestari',
        type: TransactionType.OUT,
        amount: 150000,
        margin: 2000,
        wallet: 'DANA',
        isPiutang: false,
    },
    {
        id: 'TXN1005',
        date: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
        description: 'Tarik Tunai',
        customer: 'Pelanggan',
        type: TransactionType.IN,
        amount: 200000,
        margin: 3000,
        wallet: 'BRILINK',
        isPiutang: false,
    },
    {
        id: 'TXN1006',
        date: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
        description: 'Bayar Cicilan',
        customer: 'Budi Santoso',
        type: TransactionType.OUT,
        amount: 750000,
        margin: 5000,
        wallet: 'SEABANK',
        isPiutang: false,
    },
    {
        id: 'TXN1007',
        date: new Date(new Date().setDate(new Date().getDate() - 6)).toISOString(),
        description: 'Transfer Bank',
        customer: 'Pelanggan',
        type: TransactionType.OUT,
        amount: 300000,
        margin: 3000,
        wallet: 'BRI',
        isPiutang: false,
    },
    {
        id: 'TXN1008',
        date: new Date(new Date().setDate(new Date().getDate() - 7)).toISOString(),
        description: 'Top Up E-Wallet',
        customer: 'Siti Aminah',
        type: TransactionType.OUT,
        amount: 50000,
        margin: 1500,
        wallet: 'SHOPEEPAY',
        isPiutang: true,
    },
];